export const routes = {
  explore: 'explore',
  analyse: 'analyse',
  settings: 'settings',
  config: 'config',
  users: 'users',
  roles: 'roles',
  tasks: 'tasks',
  keys: 'keys',
  billing: 'billing',
  user: '/user',
  login: '/auth/login',
  logout: '/auth/logout',
  recover: '/auth/recover',
};
