export const routes = {
  explore: 'explore',
  analyse: 'analyse',
  settings: 'settings',
  config: 'config',
  users: 'users',
  roles: 'roles',
  tasks: 'tasks',
  keys: 'keys',
  billing: 'billing',
  map: '/explore/map',
  dashboard: '/explore/dashboard',
  chart: '/explore/chart',
  series: '/explore/series',
  gallery: '/explore/gallery',
  variable: '/explore/variable',
  device: '/explore/device',
  task: '/explore/task',
  timelapse: '/explore/timelapse',
  notification: '/explore/notification',
  group: '/explore/group',
  default: '/explore/map',
  user: '/user',
  profile: '/user/profile',
  create: {
    hub: '/user/hub/create',
    node: '/explore/create',
  },
  admin: {
    hubs: 'hubs',
    users: 'users',
  },
  login: '/auth/login',
  logout: '/auth/logout',
  recover: '/auth/recover',
};
