changesetBaseRefs:
  - develop
  - origin/develop

compressionLevel: mixed

enableGlobalCache: false

supportedArchitectures:
  cpu:
    - current
    - x64
    - arm64
  libc:
    - current
    - glibc
    - musl
  os:
    - current
    - darwin
    - linux
    - win32

yarnPath: .yarn/releases/yarn-4.3.0.cjs
