import EmptySvg from './empty.svg?react';
import EnvaultIconWhiteSvg from './envault-icon-white.svg?react';
import EnvaultIconSvg from './envault-icon.svg?react';
import EnvaultInlineDarkSvg from './envault-inline-dark.svg?react';
import EnvaultInlineSvg from './envault-inline.svg?react';
import EnvaultPoweredByDarkSvg from './envault-poweredby-dark.svg?react';
import EnvaultPoweredBySvg from './envault-poweredby.svg?react';
import EnvaultStackedDarkSvg from './envault-stacked-dark.svg?react';
import EnvaultStackedSvg from './envault-stacked.svg?react';
import HubSvg from './hub.svg?react';
import RealtimeSvg from './realtime.svg?react';
import ReportSvg from './report.svg?react';
import ShareSvg from './share.svg?react';

export const EnvaultIcon = props => <EnvaultIconSvg {...props} />;
export const EnvaultIconWhite = props => <EnvaultIconWhiteSvg {...props} />;
export const EnvaultInline = props => <EnvaultInlineSvg {...props} />;
export const EnvaultInlineDark = props => <EnvaultInlineDarkSvg {...props} />;
export const EnvaultStacked = props => <EnvaultStackedSvg {...props} />;
export const EnvaultStackedDark = props => <EnvaultStackedDarkSvg {...props} />;
export const EnvaultPoweredBy = props => <EnvaultPoweredBySvg {...props} />;
export const EnvaultPoweredByDark = props => <EnvaultPoweredByDarkSvg {...props} />;
export const Share = props => <ShareSvg {...props} />;
export const Realtime = props => <RealtimeSvg {...props} />;
export const Hub = props => <HubSvg {...props} />;
export const Report = props => <ReportSvg {...props} />;
export const Empty = props => <EmptySvg {...props} />;
